### ISSUE TITLE
PSL Dataset

### ISSUE THREAD

**Issue by imsamimalik** [sign-language-processing/datasets#46]
I visited https://sign.mt/ and I saw Pakistan Sign Language listed there as one of the options for signed languages.  But here I do not see any dataset for PSL. How are you training the model for PSL?

**Comment by imsamimalik** [comment]
Is the 3D avatar and human model broken or it is not working on my side?

**Comment by AmitMY** [comment]
For PSL, we are leveraging https://spreadthesign.com/ur.pk/search/? under a special research license.
There is no training of any model involved, only https://github.com/ZurichNLP/spoken-to-signed-translation sign stitching.
Since the license does not allow, this dataset is not included here.

(As for your question about the https://github.com/sign/translate project, the 3d Avatar is not functional, but the human model should be. If you have any specific issue, please file it in that project)
